#ifndef STEROWNIKESP32_WEBTHING_ANALOGREAD_H
#define STEROWNIKESP32_WEBTHING_ANALOGREAD_H

#endif //STEROWNIKESP32_WEBTHING_ANALOGREAD_H

#define EXTERNAL_POWER_THRESHOLD 400
#define BATTERY_FULL_THRESHOLD 1300

void printAnalogReads();

void setupAnalogReads();

void poweringSetup();