#ifndef STEROWNIKESP32_WEBTHING_MAXTHERMOCOUPLE_H
#define STEROWNIKESP32_WEBTHING_MAXTHERMOCOUPLE_H

#define THERMO_DO_PIN 4
#define THERMO_CS_PIN 17
#define THERMO_CLK_PIN 2
#define TEMP_THRESHOLD 30
#endif //STEROWNIKESP32_WEBTHING_MAXTHERMOCOUPLE_H

double readThermocouple();