#ifndef STEROWNIKESP32_WEBTHING_MAXTHERMOCOUPLE_H
#define STEROWNIKESP32_WEBTHING_MAXTHERMOCOUPLE_H

#endif //STEROWNIKESP32_WEBTHING_MAXTHERMOCOUPLE_H

#define THERMO_DO_PIN 12
#define THERMO_CS_PIN 13
#define THERMO_CLK_PIN 14

double readThermocouple();